# encoding: utf-8
article = Article.find_or_create_by_uuid(:uuid => "demo")

blocks = [
  {:original => %Q{<h1 class="entry-title instapaper_title">DÉLATION – La Chine propose 8 000 dollars aux personnes qui dénonceraient les Tibétains ayant l’intention de s’immoler</h1>},
                :translation => %Q{<h1 class="entry-title instapaper_title"><font><font>Denouncement - China offers 8000 dollars to people who denounce Tibetans intending to sacrifice</font></font></h1>}
},
  {:original => %Q{<p>Depuis le début de l'année 2012, 72 moines tibétains se sont immolés par le feu pour protester contre l'occupation chinoise. Cette escalade d’actes désespérés est sans précédent depuis les violentes émeutes anti-chinoises de 2008 à Lhassa, la capitale tibétaine.</p>},
                :translation => %Q{<p><font><font>Since the beginning of 2012, 72 Tibetan monks set themselves on fire to protest against the Chinese occupation. </font><font>This escalation of acts of desperation is unprecedented since the violent anti-Chinese riots of 2008 in Lhasa, the Tibetan capital.</font></font></p>}
},
  {:original => %Q{<p><a href="http://www.opendemocracy.net/david-volodzko/burning-hearts" name="rdb-footnote-link-1" class="rdb-footnoted">Le site Opendemocracy.net révèle</a><sup class="rdb-footnote"><a href="http://www.readability.com/articles/lkhpikwl#rdb-footnote-1">1</a></sup> que les autorités de la province de Kanlho (Gannan en chinois) ont placardé des affiches qui promettent jusqu'à 8 000 dollars aux personnes qui dénonceraient <em>"les Tibétains ayant l'intention de s'immoler"</em>, arguant que ces actes provoquent <em>"une instabilité sociale dans la région."</em></p>},
                :translation => %Q{<p><a href="http://www.opendemocracy.net/david-volodzko/burning-hearts" name="rdb-footnote-link-1" class="rdb-footnoted"><font><font>Opendemocracy.net site reveals</font></font></a><sup class="rdb-footnote"><a href="http://www.readability.com/articles/lkhpikwl#rdb-footnote-1"><font><font>1</font></font></a></sup><font><font> that the authorities of the province of Kanlho (Gannan in Chinese) have put up posters promising to 8000 dollars to people who report </font></font><em><font><font>"Tibetans who intend to sacrifice"</font></font></em><font><font> , arguing that these actions cause </font></font><em><font><font>"social instability in the region."</font></font></em></p>}
},
  {:original => %Q{<p><a href="http://www.vice.com/fr/read/la-reponse-de-la-chine-aux-immolations-tibetaines" name="rdb-footnote-link-2" class="rdb-footnoted">Interrogée par le site vice.com</a><sup class="rdb-footnote"><a href="http://www.readability.com/articles/lkhpikwl#rdb-footnote-2">2</a></sup>, <strong></strong>Stéphanie Bridgen de l'association <em>Free Tibet</em>, précise que <em>"l'argent offert par la police – 50&nbsp;000 Yuan – équivaut à un an de salaire, même pour un membre du gouvernement."</em> Une somme colossale, donc, mais qui n'a pas eu l'effet escompté. Pis, les immolations se sont multipliées après la publication de cette annonce.</p>
<p><em>"L'annonce a été faite le 21 octobre, et le jour suivant, un habitant de la préfecture de Kanlho s'est suicidé. En cinq jours, la liste comptait quatre morts de plus. On n'a jamais recensé autant d'immolations que cette semaine-là. Si les Chinois pensent pourvoir les acheter, ils se trompent du tout au tout", </em>explique Stéphanie Bridgen.</p>},
                :translation => %Q{<p><a href="http://www.vice.com/fr/read/la-reponse-de-la-chine-aux-immolations-tibetaines" name="rdb-footnote-link-2" class="rdb-footnoted"><font><font>Asked by the site vice.com</font></font></a><sup class="rdb-footnote"><a href="http://www.readability.com/articles/lkhpikwl#rdb-footnote-2"><font><font>2</font></font></a></sup><font><font> ,</font></font><strong></strong><font><font>Stephanie Bridgen Association </font></font><em><font><font>Free Tibet</font></font></em><font><font> , said that </font></font><em><font><font>"the money offered by the police - 50,000 Yuan - equivalent to one year's salary, even a member of the government."</font></font></em><font><font> An enormous sum, therefore, but has not had the desired effect. </font><font>Worse, the immolations have increased after the publication of this announcement.</font></font></p>
<p><em><font><font>"The announcement was made ​​on October 21, and the next day, a resident of the prefecture Kanlho committed suicide. In five days, the list had four more deaths. Was never identified much immolations this week. If the Chinese think fill buy, they are wrong at all at all, "</font></font></em><font><font> says Stephanie Bridgen.</font></font></p>}
},
]

blocks.each do |block|
  Block.create(article: article, original: block[:original], translation: block[:translation])
end
